const path = require("path");
const ExtractTextPlugin = require("extract-text-webpack-plugin");
// Get all text generated by css and create one file
// it a plugin, so when we use it we have to declare it!""
// we have to add manually the style link 

// Loaders: preproccessing before code goes for the bundle
// Plugins: they keep files from ending in the bundle

module.exports = {
    entry: path.join(__dirname, "src/index.js"),
    output: {
            path: path.resolve(__dirname, "build"),
            filename: "bundle.js",
            publicPath: "build/"
    },
    module: {
        rules: [
            {
                use: [{
                    loader: "babel-loader"
                }],
                test: /\.js$/,
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: ExtractTextPlugin({
                    use: "css-loader"
                }),
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin("style.css")
    ],
    stats: {
        colors: true
    },
    devtool: "source-map"
}
